[tool.poetry]
name = "compilesketches"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "3.11.2"
GitPython = "3.1.31"
PyGithub = "1.58.0"
PyYAML = "6.0"
semver = "2.13.0"

[tool.poetry.group.dev.dependencies]
coverage = "7.2.2"
pytest = "7.2.2"
pytest-mock = "3.10.0"
flake8 = "5.0.4"
pep8-naming = "0.13.3"

# Provided only for use by boards platforms
# NOTE: This group is a temporary workaround that will be removed at the 2.0.0 release of the action.
[tool.poetry.group.external]
optional = true

[tool.poetry.group.external.dependencies]
pyserial = "3.5"

[tool.pytest.ini_options]
filterwarnings = [
  "error",
  "ignore::DeprecationWarning",
  "ignore::ResourceWarning"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
