name: Lint Python code

env:
  # See: https://pypi.org/project/poetry/#history
  POETRY_VERSION: 1.4.0

on:
  pull_request:
    paths:
      - '.github/workflows/lint-python.yml'
      - 'compilesketches/**.py'
      - '.python-version'
      - '**/poetry.lock'
      - '**/pyproject.toml'

  push:
    paths:
      - '.github/workflows/lint-python.yml'
      - 'compilesketches/**.py'
      - '.python-version'
      - '**/poetry.lock'
      - '**/pyproject.toml'

  # Scheduled trigger checks for workflow failures resulting from updates to the linting tools
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"

  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: |
          pipx \
            install \
              poetry==${{ env.POETRY_VERSION }}

      - name: Install Python Dependencies
        run: |
          poetry \
            install \
            --only dev

      - name: Lint with flake8
        env:
          PYTHON_PROJECT_PATH: ${GITHUB_WORKSPACE}/compilesketches
        run: |
          poetry run flake8 --config "${{ env.PYTHON_PROJECT_PATH }}/.flake8" --show-source "${{ env.PYTHON_PROJECT_PATH }}"
