name: Lint Python code

on:
  pull_request:
    paths:
      - '.github/workflows/lint-python.yml'
      - 'compilesketches/**.py'
      - '.python-version'

  push:
    paths:
      - '.github/workflows/lint-python.yml'
      - 'compilesketches/**.py'
      - '.python-version'

  # Scheduled trigger checks for workflow failures resulting from updates to the linting tools
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"

  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version-file: .python-version

      - name: Run the set up script
        id: setup
        run: |
          "${{ github.workspace }}/action-setup.sh"

      - name: Install flake8
        run: |
          source "${{ steps.setup.outputs.python-venv-activate-script-path }}"
          python \
            -m \
              pip install \
                flake8 \
                pep8-naming

      - name: Lint with flake8
        env:
          PYTHON_PROJECT_PATH: ${GITHUB_WORKSPACE}/compilesketches
        run: |
          source "${{ steps.setup.outputs.python-venv-activate-script-path }}"
          flake8 --config "${{ env.PYTHON_PROJECT_PATH }}/.flake8" --show-source "${{ env.PYTHON_PROJECT_PATH }}"
